### ISSUE TITLE
Слеши в путях

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#11]
Получаю вот такой генерик:

```
<?xml version="1.0" encoding="utf-8"?>
<coverage version="1">
    <file path="src\IRP\src\CommonModules\UsersEvent\Module.bsl">
        <lineToCover lineNumber="93" covered="true"/>
        <lineToCover lineNumber="94" covered="true"/>
    </file>     
    <file path="src\IRP\src\CommonModules\Saas\Module.bsl">
        <lineToCover lineNumber="2" covered="true"/>
        <lineToCover lineNumber="3" covered="true"/>
    </file>
```
Но в сонаре пути стоят обратными слешами, и из-за этого - система ничего не подгружает.
Пока не исправлю на
```
<?xml version="1.0" encoding="utf-8"?>
<coverage version="1">
    <file path="src/IRP/src/CommonModules/UsersEvent/Module.bsl">
        <lineToCover lineNumber="93" covered="true"/>
        <lineToCover lineNumber="94" covered="true"/>
    </file>     
    <file path="src/IRP/src/CommonModules/Saas/Module.bsl">
        <lineToCover lineNumber="2" covered="true"/>
        <lineToCover lineNumber="3" covered="true"/>
    </file>
```
Так что лучше, наверное - как то иметь возможность явного указания того, какой слешь тебе нужен. Хотя, странно это все, никогда бы не подумал на такое...

**Comment by yukon39** [comment]
Сонар сканер на винде запускается? И конвертация там же?

Рекомендовано использовать нативные разделители в пути:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
> For all report files use the native path separator of your operating system for path items. This is backslash (\) on Microsoft Windows and slash (/) on Linux. 

Надо разобраться. Опять же "у меня работает" - Windows 10 1909

**Comment by yukon39** [comment]
Хотя в принципе, довод разумный - конвертация и сам анализ Сонара могут происходить на разных машинах и, как следствие, разных ОС - Linux/Windows.

**Comment by DitriXNew** [comment]
На последнем релизе проблема решена
