### ISSUE TITLE
Сброс кеша в файл

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#14]
Как я понимаю - замер включается один раз и работает до конца.
Вопрос отсюда - можно ли как то системе сказать - периодамы сбрасывать кэш в файл csv, а не чтобы он хранился до последнего.
Или он всетаки куда-то скидывается во временные файлы?

**Comment by yukon39** [comment]
Сбором покрытия сейчас занимается Coverage41C. Насколько я понимаю такой возможности на данный момент не реализовано.

**Comment by DitriXNew** [comment]
Уже не актуально. Большие объемы нормально проходят.
