### ISSUE TITLE
Перевод конфига на инглишь

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#15]
Есть пример конфига:
https://github.com/yukon39/coverage-cli/blob/master/examples/convert-config.json
Можно ли сделать его с английскими параметрами?

**Comment by yukon39** [comment]
Можно, конечно.

**Comment by yukon39** [comment]
Переработал структуру конфигурационного файла: https://github.com/yukon39/coverage-cli/commit/b0aecccd01d89bfaec282d24f83fcf5915cfbdd3
