### ISSUE TITLE
Добавить в локализационных строках, где надо - НСтр

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#17]
Как добавите где надо - я сразу сделаю перевод на инглишь.
Без этого тяжко, надо вечно писать кодировки, и когда все вокруг на инглише - русский немного сбивает :)

**Comment by yukon39** [comment]
Все локализованные строки вынесены во внутренние пакеты `internal/localization` https://github.com/yukon39/coverage-cli/commit/8e18058eb372f5c43638421dd5523868c8f335dc

@DitriXNew - так удобно получится перевести?
