### ISSUE TITLE
Два одновременных запуска в CI контуре

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#25]
Сейчас есть проблема, если я запускаю на одной системе два сборщика, то вопрос, как мне остановить нужный?

in directory: C:\BuildAgentSecond\work\161527a3295c878a
?????????? - Created pid file: C:\BuildAgentSecond\temp\buildTmp\coverage.9200.pid
Process exited with code 0

Вот лог при старте, отлично, а если я два стартанул и теперь вызываю стоп, какой из них остановиться?

**Comment by DitriXNew** [comment]
понял, пришлось написать такой скрипт

```
$cmdOutput = cmd /c coverage-cli start --infobase irp_nt  --debugger http://localhost:1550 --output Cover.csv '2>&1' | Out-String
$cmdOutput

$PIDArray = $cmdOutput.Split('.')
$PID_ID = $PIDArray[ $PIDArray.Count - 2 ]
$PID_ID

Start-Sleep -s 5
$cmdOutput = cmd /c coverage-cli stop -p $PID_ID '2>&1' | Out-String
$cmdOutput
```

**Comment by DitriXNew** [comment]
Нифига, почему то start зависает при работе через powershell, и ничего не выдает. При чем если в момент зависания в другой консоли сказать стоп, то тогда и этот скрипт развисает и дает всю инфу.
Вобщем не понятно, как парсить на PID ID в таком случае ответ, если через powershell его не удается получить :(

**Comment by DitriXNew** [comment]
Вобщем намучался я конкретно.
Надо что то придумать, например - я указываю через параметр при старте путь к файлу, и при стопе - тоже его указываю. Сам клиент считывает его и останавливает процессы.
Иначе - ничего не получается, так как через PS ничего нормально не отрабатывает.

**Comment by DitriXNew** [comment]
Проблема появляется в CI контуре, похоже что если остановка и запуск разнесены по времени, то при следуюзей остановке - система не видит pid файл, даже если писать просто стоп без параметров

**Comment by yukon39** [comment]
Занятно получается. Попробую посмотреть, что там за беда с PS.

**Comment by DitriXNew** [comment]
Проблема на последней версии решилась.
