### ISSUE TITLE
Задать параметр ограничения памяти

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#33]
Вопрос, у меня при старте покрытия - система сразу отжирает  4-8гигов.
Отжирает сам жарник Covrage41C, меня оттуда послали, и сказали что это не баг а фича, и надо ограничивать отдельно.
https://github.com/1c-syntax/Coverage41C/issues/119
Вопрос - может у тебя сделать некий параметр, который можно будет передавать и ограничивать рост памяти таким образом?

**Comment by yukon39** [comment]
Можно конечно.

**Comment by yukon39** [comment]
@DitriXNew Достаточно же запустить Coverage c дополнительными ключами -Xms и -Xmx?
