### ISSUE TITLE
[BUG] ОбработчикиФормата не описывает МодульФормы и МодульКоманды

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#9]
Из-за этого ловится крит:
ОШИБКА - Не найден обработчик для вида программного модуля "32e087ab-1491-49b6-aba7-43571b41ac2b"

**Comment by yukon39** [comment]
Еще не поддерживается. Как раз на следующий заход запланированы.

**Comment by yukon39** [comment]
@DitriXNew Такой вопрос - как вызываешь модуль команды? Вручную или BDD?

**Comment by DitriXNew** [comment]
ну сейчас пайплайн настраиваю, и пока просто вручную.

**Comment by yukon39** [comment]
Реализовано в 0.7.0
